-- 1. 테이블 생성 (svclist.xlsx 의 구조를 반영)
CREATE TABLE IF NOT EXISTS sm_svclist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name VARCHAR(100),
    center_name VARCHAR(100),
    process_ym VARCHAR(10),
    sm_id VARCHAR(50),
    sm_name VARCHAR(100),
    day_01 NUMERIC, day_02 NUMERIC, day_03 NUMERIC, day_04 NUMERIC, day_05 NUMERIC,
    day_06 NUMERIC, day_07 NUMERIC, day_08 NUMERIC, day_09 NUMERIC, day_10 NUMERIC,
    day_11 NUMERIC, day_12 NUMERIC, day_13 NUMERIC, day_14 NUMERIC, day_15 NUMERIC,
    day_16 NUMERIC, day_17 NUMERIC, day_18 NUMERIC, day_19 NUMERIC, day_20 NUMERIC,
    day_21 NUMERIC, day_22 NUMERIC, day_23 NUMERIC, day_24 NUMERIC, day_25 NUMERIC,
    day_26 NUMERIC, day_27 NUMERIC, day_28 NUMERIC, day_29 NUMERIC, day_30 NUMERIC,
    day_31 NUMERIC
);

-- 2. 권한(Role) 부여: 익명(anon) 사용자가 테이블에 접근/수정할 수 있도록 허용
GRANT ALL ON sm_svclist TO anon;
GRANT ALL ON sm_svclist TO authenticated;
GRANT ALL ON sm_svclist TO service_role;

-- 3. 혹시 RLS가 활성화된 경우를 대비해 RLS 정책을 추가하거나 강제 비활성화
ALTER TABLE sm_svclist DISABLE ROW LEVEL SECURITY;
