-- 1. 기존 뷰 및 테이블 완전 삭제 (CASCADE를 사용하여 의존성 있는 뷰까지 안전하게 삭제)
DROP TABLE IF EXISTS chat_logs CASCADE;

-- 2. 원본 데이터 항목명(camelCase)으로 테이블을 아예 새롭게 생성
CREATE TABLE chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "chatId" TEXT,
    "chatDate" DATE,
    "chatHour" INTEGER,
    "userName" TEXT,
    "userNo" TEXT,
    "userDeptName" TEXT,
    "questionTypeCd" TEXT,
    "aiResultStatus" TEXT,
    "userAction" TEXT,
    "prodLvl2Cd" TEXT,
    "prodLvl2Name" TEXT,
    "prodLvl3Cd" TEXT,
    "prodLvl3Name" TEXT,
    "chatMsg" TEXT,
    "userActionValue" TEXT
);

-- RLS(Row Level Security) 설정 (Python 스크립트(Anon 키)에서 데이터 삽입/조회를 허용하기 위함)
ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access for anon users" ON chat_logs;
CREATE POLICY "Enable all access for anon users"
  ON chat_logs
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- API 익명(Anon) 접근 권한 부여
GRANT ALL ON TABLE chat_logs TO anon;
GRANT USAGE, SELECT ON SEQUENCE chat_logs_id_seq TO anon;

-- 3. 뷰 재생성 (변경된 컬럼명 적용)

-- KPI 뷰
CREATE VIEW v_kpis AS
SELECT
  COUNT(DISTINCT COALESCE("userName", '알수없음') || '(' || COALESCE("userNo", '알수없음') || ')') AS total_users,
  COUNT(CASE WHEN "userAction" = 'QUESTION' THEN id END) AS total_inquiries,
  COUNT(CASE WHEN "userAction" = 'QUESTION' AND "aiResultStatus" = 'SUCCESS' THEN id END) AS resolved_count,
  -- 평일 일평균 사용자 계산을 위한 일자별 사번 기준 접속자 총합 (주말 및 주요 공휴일 제외)
  -- 2026년 주요 공휴일 및 대체공휴일을 하드코딩으로 제외합니다.
  COUNT(DISTINCT CASE 
    WHEN EXTRACT(ISODOW FROM "chatDate") < 6 
    AND TO_CHAR("chatDate", 'MM-DD') NOT IN ('01-01', '02-16', '02-17', '02-18', '03-02', '05-01', '05-05', '05-25', '06-03', '07-17', '08-17', '09-24', '09-25', '10-05', '10-09', '12-25') 
    THEN "userNo" || '_' || TO_CHAR("chatDate", 'YYYY-MM-DD') 
  END) AS sum_daily_users_wd,
  
  -- 평일 기준 총 검색건수 (주말 및 공휴일 제외)
  COUNT(CASE 
    WHEN "userAction" = 'QUESTION' 
    AND EXTRACT(ISODOW FROM "chatDate") < 6 
    AND TO_CHAR("chatDate", 'MM-DD') NOT IN ('01-01', '02-16', '02-17', '02-18', '03-02', '05-01', '05-05', '05-25', '06-03', '07-17', '08-17', '09-24', '09-25', '10-05', '10-09', '12-25') 
    THEN id 
  END) AS total_inquiries_wd,
  
  -- 평일 기준 활성 일수 (주말 및 공휴일 제외)
  COUNT(DISTINCT CASE 
    WHEN "userAction" = 'QUESTION' 
    AND EXTRACT(ISODOW FROM "chatDate") < 6 
    AND TO_CHAR("chatDate", 'MM-DD') NOT IN ('01-01', '02-16', '02-17', '02-18', '03-02', '05-01', '05-05', '05-25', '06-03', '07-17', '08-17', '09-24', '09-25', '10-05', '10-09', '12-25') 
    THEN "chatDate" 
  END) AS active_days_wd
FROM chat_logs;

-- 시간대별 차트 뷰
CREATE VIEW v_hourly AS
SELECT
  "chatHour" AS chat_hour,
  COUNT(id) AS inquiry_count
FROM chat_logs
WHERE "userAction" = 'QUESTION'
GROUP BY "chatHour";

-- 문의 유형 차트 뷰
CREATE VIEW v_types AS
SELECT
  "questionTypeCd" AS question_type,
  COUNT(id) AS type_count
FROM chat_logs
WHERE "userAction" = 'QUESTION'
GROUP BY "questionTypeCd";

-- 상위 사용자 10명 뷰
CREATE VIEW v_top_users AS
SELECT
  "userName" AS user_name,
  "userNo" AS user_no,
  COUNT(id) AS inquiry_count
FROM chat_logs
WHERE "userAction" = 'QUESTION'
GROUP BY "userName", "userNo"
ORDER BY COUNT(id) DESC
LIMIT 10;

-- 상위 센터 10곳 뷰
CREATE VIEW v_top_centers AS
SELECT
  "userDeptName" AS user_dept_name,
  COUNT(id) AS inquiry_count
FROM chat_logs
WHERE "userAction" = 'QUESTION'
GROUP BY "userDeptName"
ORDER BY COUNT(id) DESC
LIMIT 10;
